CREATE DATABASE IF NOT EXISTS beyond_the_feed CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE beyond_the_feed;

CREATE TABLE categories (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100) NOT NULL UNIQUE, slug VARCHAR(100) NOT NULL UNIQUE, description VARCHAR(255));
CREATE TABLE users (id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(120) NOT NULL, email VARCHAR(180) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, role ENUM('READER','EDITOR','ADMIN') NOT NULL DEFAULT 'READER', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE articles (id INT PRIMARY KEY AUTO_INCREMENT, category_id INT NOT NULL, author_id INT NULL, title VARCHAR(220) NOT NULL, slug VARCHAR(240) NOT NULL UNIQUE, excerpt TEXT NOT NULL, body TEXT NOT NULL, image_url VARCHAR(500), read_time VARCHAR(30), featured BOOLEAN NOT NULL DEFAULT FALSE, published BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, CONSTRAINT fk_article_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE RESTRICT, CONSTRAINT fk_article_author FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE SET NULL);
CREATE TABLE comments (id INT PRIMARY KEY AUTO_INCREMENT, article_id INT NOT NULL, user_id INT NULL, body TEXT NOT NULL, approved BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_comment_article FOREIGN KEY (article_id) REFERENCES articles(id) ON DELETE CASCADE, CONSTRAINT fk_comment_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL);

INSERT INTO categories (name, slug, description) VALUES ('Instagram & The Mind','mind','Comparison, attention, self-expression and the inspiration we find in a shared visual world.'),('Creativity & Communities','creativity','Creators, niche communities and the collaborations that make discovery feel human.'),('Instagram for Business','business','How small businesses and independent creators turn a feed into a digital storefront.'),('Healthy Digital Habits','habits','Mindful scrolling, intentional use and boundaries for a healthier relationship with the feed.');
INSERT INTO users (name,email,password_hash,role) VALUES ('Maya Chen','maya@beyondthefeed.com','demo-hash','EDITOR'),('Noah Williams','noah@beyondthefeed.com','demo-hash','EDITOR'),('Ari Okafor','ari@beyondthefeed.com','demo-hash','EDITOR'),('Lena Ortiz','lena@beyondthefeed.com','demo-hash','EDITOR');
INSERT INTO articles (category_id,author_id,title,slug,excerpt,body,image_url,read_time,featured) VALUES
(1,1,'Reels and the Restless Mind','reels-and-the-restless-mind','What short-form video gives us, what it takes from our attention, and why the best inspiration still needs a stopping point.','Instagram Reels can turn a new recipe, dance, idea or point of view into something we discover between two ordinary moments. The speed is energising, but the next clip is always waiting, making it easy to confuse endless novelty with genuine inspiration. A healthier relationship with Reels leaves room to save what matters, make something of our own, and close the app before the feed chooses the next thought for us.','https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&w=1200&q=85','6 min read',TRUE),
(1,2,'Close Friends, Smaller Internet','close-friends-smaller-internet','Why Instagram Stories and private circles are making everyday sharing feel personal again.','The green ring of Close Friends changes the feeling of posting. A voice note, a half-finished dinner or a silly Story can travel to a smaller audience where performance gives way to recognition. Private sharing does not make Instagram free of pressure, but it gives people a way to keep the social pleasure of the platform without turning every moment into a public audition.','https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=85','5 min read',FALSE),
(2,3,'Photo Dumps After the Perfect Post','photo-dumps-after-the-perfect-post','How carousels, photo dumps and looser aesthetics are changing what feels worth sharing on Instagram.','The photo dump made room for the blurry, the ordinary and the almost-forgotten. Carousels let a weekend unfold instead of asking one polished image to represent it, while new visual trends keep moving between candid, nostalgic and deliberately unfiltered. The shift is not a complete escape from curation, but it makes Instagram feel more like a scrapbook and less like a row of billboards.','https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=900&q=85','7 min read',FALSE),
(2,3,'When the Algorithm Finds Your People','when-the-algorithm-finds-your-people','Inside the strange joy of niche pages, interest-based communities and discovery that leads somewhere unexpected.','A search for one small interest can open onto an entire Instagram neighborhood: fan pages, makers, explainers, organizers and people who understand the reference immediately. Discovery can become a rabbit hole, but it can also connect a beginner to a mentor or a lonely idea to its audience. The challenge is to let recommendation lead us toward participation, not only toward more watching.','https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=900&q=85','8 min read',FALSE),
(3,4,'The Link in Bio Is a Shop Window','the-link-in-bio-is-a-shop-window','How small businesses use Instagram to tell a story, build trust and turn discovery into a real customer relationship.','For a small business, Instagram can be a storefront before it can afford a storefront. A process video, a customer message and a thoughtful carousel let people meet the maker behind the object, while the link in bio turns curiosity into a visit or a sale. The work is still demanding, and no platform should be the whole business, but Instagram can give independent brands a visible place to begin.','https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=900&q=85','6 min read',FALSE),
(3,4,'Paid Partnership, Personal Voice','paid-partnership-personal-voice','What happens when creators build a business through brand collaborations without losing the trust of their community.','The creator economy has made personal taste part of the workday. The strongest brand collaborations feel less like an interruption and more like a useful extension of a creator’s practice, with room for disclosure, criticism and a real point of view. Trust is not created by a perfect campaign; it is built when a community can tell what a creator actually uses, believes and would still talk about without a sponsor.','https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=900&q=85','7 min read',FALSE),
(4,1,'Stories Without the Scoreboard','stories-without-the-scoreboard','Why some people are changing how they use Instagram, from chasing likes to sharing with intention.','Instagram Stories once made everyday sharing feel lighter, but even temporary posts can become a quiet measure of who watched and who did not. Some people are responding by hiding like counts, posting less often, using Close Friends or making work that asks for conversation instead of applause. The goal is not to reject visibility; it is to choose an audience and a reason before the numbers choose them for us.','https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=85','5 min read',FALSE),
(4,1,'A Feed You Can Live With','a-feed-you-can-live-with','Small changes for mindful scrolling, from curating your follows to making space for life away from the screen.','Digital wellbeing on Instagram is less about one perfect rule than a series of small choices. Mute what makes you compare, follow people who teach or delight you, save inspiration for later and give the app a place in your day rather than letting it fill every pause. The feed can hold creativity, friendship and practical help, but a life beyond it needs some attention left over.','https://images.unsplash.com/photo-1499209974431-9dddcece7f88?auto=format&fit=crop&w=900&q=85','6 min read',FALSE);
